using TCSA.V2026.Helpers;

namespace TCSA.V2026.UnitTests.Helpers;

[TestFixture]
public class FlagHelperTests
{
    [Test]
    public void GetFlag_ShouldReturnEarthImage_WhenCountryIsNullOrEmpty()
    {
        // Arrange
        string country = null;

        // Act
        var result = FlagHelper.GetFlag(country);

        // Assert
        Assert.That(result, Is.EqualTo("img/flags/earth.png"));
    }

    [Test]
    public void GetFlag_ShouldReturnEarthImage_WhenCountryNotFound()
    {
        // Arrange
        string country = "Unknown Country";

        // Act
        var result = FlagHelper.GetFlag(country);

        // Assert
        Assert.That(result, Is.EqualTo("img/flags/earth.png"));
    }

    [TestCase("Afghanistan", "img/flags/afghanistan.png")]
    [TestCase("Albania", "img/flags/albania.png")]
    [TestCase("Algeria", "img/flags/algeria.png")]
    [TestCase("American Samoa", "img/flags/american-samoa.png")]
    [TestCase("Andorra", "img/flags/andorra.png")]
    [TestCase("Angola", "img/flags/angola.png")]
    [TestCase("Anguilla", "img/flags/anguilla.png")]
    [TestCase("Antarctica", "img/flags/antarctica.png")]
    [TestCase("Antigua and Barbuda", "img/flags/antigua-and-barbuda.png")]
    [TestCase("Argentina", "img/flags/argentina.png")]
    [TestCase("Armenia", "img/flags/armenia.png")]
    [TestCase("Aruba", "img/flags/aruba.png")]
    [TestCase("Australia", "img/flags/australia.png")]
    [TestCase("Austria", "img/flags/austria.png")]
    [TestCase("Azerbaijan", "img/flags/azerbaijan.png")]
    [TestCase("Bahamas", "img/flags/bahamas.png")]
    [TestCase("Bahrain", "img/flags/bahrain.png")]
    [TestCase("Bangladesh", "img/flags/bangladesh.png")]
    [TestCase("Barbados", "img/flags/barbados.png")]
    [TestCase("Belarus", "img/flags/belarus.png")]
    [TestCase("Belgium", "img/flags/belgium.png")]
    [TestCase("Belize", "img/flags/belize.png")]
    [TestCase("Benin", "img/flags/benin.png")]
    [TestCase("Bermuda", "img/flags/bermuda.png")]
    [TestCase("Bhutan", "img/flags/bhutan.png")]
    [TestCase("Bolivia", "img/flags/bolivia.png")]
    [TestCase("Bosnia and Herzegovina", "img/flags/bosnia-and-herzegovina.png")]
    [TestCase("Botswana", "img/flags/botswana.png")]
    [TestCase("Bouvet Island", "img/flags/bouvet-island.png")]
    [TestCase("Brazil", "img/flags/brazil.png")]
    [TestCase("British Indian Ocean Territory", "img/flags/british-indian-ocean-territory.png")]
    [TestCase("Brunei Darussalam", "img/flags/brunei-darussalam.png")]
    [TestCase("Bulgaria", "img/flags/bulgaria.png")]
    [TestCase("Burkina Faso", "img/flags/burkina-faso.png")]
    [TestCase("Burundi", "img/flags/burundi.png")]
    [TestCase("Cabo Verde", "img/flags/cabo-verde.png")]
    [TestCase("Cambodia", "img/flags/cambodia.png")]
    [TestCase("Cameroon", "img/flags/cameroon.png")]
    [TestCase("Canada", "img/flags/canada.png")]
    [TestCase("Cayman Islands", "img/flags/cayman-islands.png")]
    [TestCase("Central African Republic", "img/flags/central-african-republic.png")]
    [TestCase("Chad", "img/flags/chad.png")]
    [TestCase("Chile", "img/flags/chile.png")]
    [TestCase("China", "img/flags/china.png")]
    [TestCase("Christmas Island", "img/flags/christmas-island.png")]
    [TestCase("Cocos (Keeling) Islands", "img/flags/cocos-(keeling)-islands.png")]
    [TestCase("Colombia", "img/flags/colombia.png")]
    [TestCase("Comoros", "img/flags/comoros.png")]
    [TestCase("Congo", "img/flags/congo.png")]
    [TestCase("Democratic Republic of the Congo", "img/flags/democratic-republic-of-the-congo.png")]
    [TestCase("Cook Islands", "img/flags/cook-islands.png")]
    [TestCase("Costa Rica", "img/flags/costa-rica.png")]
    [TestCase("Croatia", "img/flags/croatia.png")]
    [TestCase("Cuba", "img/flags/cuba.png")]
    [TestCase("Cyprus", "img/flags/cyprus.png")]
    [TestCase("Czechia", "img/flags/czechia.png")]
    [TestCase("Côte d'Ivoire", "img/flags/côte-d'ivoire.png")]
    [TestCase("Denmark", "img/flags/denmark.png")]
    [TestCase("Djibouti", "img/flags/djibouti.png")]
    [TestCase("Dominica", "img/flags/dominica.png")]
    [TestCase("Dominican Republic", "img/flags/dominican-republic.png")]
    [TestCase("Ecuador", "img/flags/ecuador.png")]
    [TestCase("Egypt", "img/flags/egypt.png")]
    [TestCase("El Salvador", "img/flags/el-salvador.png")]
    [TestCase("Equatorial Guinea", "img/flags/equatorial-guinea.png")]
    [TestCase("Eritrea", "img/flags/eritrea.png")]
    [TestCase("Estonia", "img/flags/estonia.png")]
    [TestCase("Eswatini", "img/flags/eswatini.png")]
    [TestCase("Ethiopia", "img/flags/ethiopia.png")]
    [TestCase("Falkland Islands (Malvinas)", "img/flags/falkland-islands-(malvinas).png")]
    [TestCase("Faroe Islands", "img/flags/faroe-islands.png")]
    [TestCase("Fiji", "img/flags/fiji.png")]
    [TestCase("Finland", "img/flags/finland.png")]
    [TestCase("France", "img/flags/france.png")]
    [TestCase("French Guiana", "img/flags/french-guiana.png")]
    [TestCase("French Polynesia", "img/flags/french-polynesia.png")]
    [TestCase("French Southern Territories", "img/flags/french-southern-territories.png")]
    [TestCase("Gabon", "img/flags/gabon.png")]
    [TestCase("Gambia", "img/flags/gambia.png")]
    [TestCase("Georgia", "img/flags/georgia.png")]
    [TestCase("Germany", "img/flags/germany.png")]
    [TestCase("Ghana", "img/flags/ghana.png")]
    [TestCase("Gibraltar", "img/flags/gibraltar.png")]
    [TestCase("Greece", "img/flags/greece.png")]
    [TestCase("Greenland", "img/flags/greenland.png")]
    [TestCase("Grenada", "img/flags/grenada.png")]
    [TestCase("Guadeloupe", "img/flags/guadeloupe.png")]
    [TestCase("Guam", "img/flags/guam.png")]
    [TestCase("Guatemala", "img/flags/guatemala.png")]
    [TestCase("Guernsey", "img/flags/guernsey.png")]
    [TestCase("Guinea", "img/flags/guinea.png")]
    [TestCase("Guinea-Bissau", "img/flags/guinea-bissau.png")]
    [TestCase("Guyana", "img/flags/guyana.png")]
    [TestCase("Haiti", "img/flags/haiti.png")]
    [TestCase("Heard Island and McDonald Islands", "img/flags/heard-island-and-mcdonald-islands.png")]
    [TestCase("Holy See", "img/flags/holy-see.png")]
    [TestCase("Honduras", "img/flags/honduras.png")]
    [TestCase("Hong Kong", "img/flags/hong-kong.png")]
    [TestCase("Hungary", "img/flags/hungary.png")]
    [TestCase("Iceland", "img/flags/iceland.png")]
    [TestCase("India", "img/flags/india.png")]
    [TestCase("Indonesia", "img/flags/indonesia.png")]
    [TestCase("Iran", "img/flags/iran.png")]
    [TestCase("Iraq", "img/flags/iraq.png")]
    [TestCase("Ireland", "img/flags/ireland.png")]
    [TestCase("Isle of Man", "img/flags/isle-of-man.png")]
    [TestCase("Israel", "img/flags/israel.png")]
    [TestCase("Italy", "img/flags/italy.png")]
    [TestCase("Jamaica", "img/flags/jamaica.png")]
    [TestCase("Japan", "img/flags/japan.png")]
    [TestCase("Jersey", "img/flags/jersey.png")]
    [TestCase("Jordan", "img/flags/jordan.png")]
    [TestCase("Kazakhstan", "img/flags/kazakhstan.png")]
    [TestCase("Kenya", "img/flags/kenya.png")]
    [TestCase("Kiribati", "img/flags/kiribati.png")]
    [TestCase("Korea (North)", "img/flags/korea-(north).png")]
    [TestCase("Korea (South)", "img/flags/korea-(south).png")]
    [TestCase("Kuwait", "img/flags/kuwait.png")]
    [TestCase("Kyrgyzstan", "img/flags/kyrgyzstan.png")]
    [TestCase("Lao People's Democratic Republic", "img/flags/lao-people's-democratic-republic.png")]
    [TestCase("Latvia", "img/flags/latvia.png")]
    [TestCase("Lebanon", "img/flags/lebanon.png")]
    [TestCase("Lesotho", "img/flags/lesotho.png")]
    [TestCase("Liberia", "img/flags/liberia.png")]
    [TestCase("Libya", "img/flags/libya.png")]
    [TestCase("Liechtenstein", "img/flags/liechtenstein.png")]
    [TestCase("Lithuania", "img/flags/lithuania.png")]
    [TestCase("Luxembourg", "img/flags/luxembourg.png")]
    [TestCase("Macao", "img/flags/macao.png")]
    [TestCase("Madagascar", "img/flags/madagascar.png")]
    [TestCase("Malawi", "img/flags/malawi.png")]
    [TestCase("Malaysia", "img/flags/malaysia.png")]
    [TestCase("Maldives", "img/flags/maldives.png")]
    [TestCase("Mali", "img/flags/mali.png")]
    [TestCase("Malta", "img/flags/malta.png")]
    [TestCase("Marshall Islands", "img/flags/marshall-islands.png")]
    [TestCase("Martinique", "img/flags/martinique.png")]
    [TestCase("Mauritania", "img/flags/mauritania.png")]
    [TestCase("Mauritius", "img/flags/mauritius.png")]
    [TestCase("Mayotte", "img/flags/mayotte.png")]
    [TestCase("Mexico", "img/flags/mexico.png")]
    [TestCase("Micronesia", "img/flags/micronesia.png")]
    [TestCase("Moldova", "img/flags/moldova.png")]
    [TestCase("Monaco", "img/flags/monaco.png")]
    [TestCase("Mongolia", "img/flags/mongolia.png")]
    [TestCase("Montenegro", "img/flags/montenegro.png")]
    [TestCase("Montserrat", "img/flags/montserrat.png")]
    [TestCase("Morocco", "img/flags/morocco.png")]
    [TestCase("Mozambique", "img/flags/mozambique.png")]
    [TestCase("Myanmar", "img/flags/myanmar.png")]
    [TestCase("Namibia", "img/flags/namibia.png")]
    [TestCase("Nauru", "img/flags/nauru.png")]
    [TestCase("Nepal", "img/flags/nepal.png")]
    [TestCase("Netherlands", "img/flags/netherlands.png")]
    [TestCase("New Caledonia", "img/flags/new-caledonia.png")]
    [TestCase("New Zealand", "img/flags/new-zealand.png")]
    [TestCase("Nicaragua", "img/flags/nicaragua.png")]
    [TestCase("Niger", "img/flags/niger.png")]
    [TestCase("Nigeria", "img/flags/nigeria.png")]
    [TestCase("Niue", "img/flags/niue.png")]
    [TestCase("Norfolk Island", "img/flags/norfolk-island.png")]
    [TestCase("North Macedonia", "img/flags/north-macedonia.png")]
    [TestCase("Northern Mariana Islands", "img/flags/northern-mariana-islands.png")]
    [TestCase("Norway", "img/flags/norway.png")]
    [TestCase("Oman", "img/flags/oman.png")]
    [TestCase("Pakistan", "img/flags/pakistan.png")]
    [TestCase("Palau", "img/flags/palau.png")]
    [TestCase("Palestine", "img/flags/palestine.png")]
    [TestCase("Panama", "img/flags/panama.png")]
    [TestCase("Papua New Guinea", "img/flags/papua-new-guinea.png")]
    [TestCase("Paraguay", "img/flags/paraguay.png")]
    [TestCase("Peru", "img/flags/peru.png")]
    [TestCase("Philippines", "img/flags/philippines.png")]
    [TestCase("Pitcairn", "img/flags/pitcairn.png")]
    [TestCase("Poland", "img/flags/poland.png")]
    [TestCase("Portugal", "img/flags/portugal.png")]
    [TestCase("Puerto Rico", "img/flags/puerto-rico.png")]
    [TestCase("Qatar", "img/flags/qatar.png")]
    [TestCase("Romania", "img/flags/romania.png")]
    [TestCase("Russia", "img/flags/russia.png")]
    [TestCase("Rwanda", "img/flags/rwanda.png")]
    [TestCase("Réunion", "img/flags/réunion.png")]
    [TestCase("Saint Barthélemy", "img/flags/saint-barthélemy.png")]
    [TestCase("Saint Helena", "img/flags/saint-helena.png")]
    [TestCase("Saint Kitts and Nevis", "img/flags/saint-kitts-and-nevis.png")]
    [TestCase("Saint Lucia", "img/flags/saint-lucia.png")]
    [TestCase("Saint Martin", "img/flags/saint-martin.png")]
    [TestCase("Saint Pierre and Miquelon", "img/flags/saint-pierre-and-miquelon.png")]
    [TestCase("Saint Vincent and the Grenadines", "img/flags/saint-vincent-and-the-grenadines.png")]
    [TestCase("Samoa", "img/flags/samoa.png")]
    [TestCase("San Marino", "img/flags/san-marino.png")]
    [TestCase("Sao Tome and Principe", "img/flags/sao-tome-and-principe.png")]
    [TestCase("Saudi Arabia", "img/flags/saudi-arabia.png")]
    [TestCase("Senegal", "img/flags/senegal.png")]
    [TestCase("Serbia", "img/flags/serbia.png")]
    [TestCase("Seychelles", "img/flags/seychelles.png")]
    [TestCase("Sierra Leone", "img/flags/sierra-leone.png")]
    [TestCase("Singapore", "img/flags/singapore.png")]
    [TestCase("Sint Maarten", "img/flags/sint-maarten.png")]
    [TestCase("Slovakia", "img/flags/slovakia.png")]
    [TestCase("Slovenia", "img/flags/slovenia.png")]
    [TestCase("Solomon Islands", "img/flags/solomon-islands.png")]
    [TestCase("Somalia", "img/flags/somalia.png")]
    [TestCase("South Africa", "img/flags/south-africa.png")]
    [TestCase("South Georgia and the South Sandwich Islands", "img/flags/south-georgia-and-the-south-sandwich-islands.png")]
    [TestCase("South Sudan", "img/flags/south-sudan.png")]
    [TestCase("Spain", "img/flags/spain.png")]
    [TestCase("Sri Lanka", "img/flags/sri-lanka.png")]
    [TestCase("Sudan", "img/flags/sudan.png")]
    [TestCase("Suriname", "img/flags/suriname.png")]
    [TestCase("Sweden", "img/flags/sweden.png")]
    [TestCase("Switzerland", "img/flags/switzerland.png")]
    [TestCase("Syrian Arab Republic", "img/flags/syrian-arab-republic.png")]
    [TestCase("Taiwan", "img/flags/taiwan.png")]
    [TestCase("Tajikistan", "img/flags/tajikistan.png")]
    [TestCase("Tanzania", "img/flags/tanzania.png")]
    [TestCase("Thailand", "img/flags/thailand.png")]
    [TestCase("Timor-Leste", "img/flags/timor-leste.png")]
    [TestCase("Togo", "img/flags/togo.png")]
    [TestCase("Tokelau", "img/flags/tokelau.png")]
    [TestCase("Tonga", "img/flags/tonga.png")]
    [TestCase("Trinidad and Tobago", "img/flags/trinidad-and-tobago.png")]
    [TestCase("Tunisia", "img/flags/tunisia.png")]
    [TestCase("Turkey", "img/flags/turkey.png")]
    [TestCase("Turkmenistan", "img/flags/turkmenistan.png")]
    [TestCase("Tuvalu", "img/flags/tuvalu.png")]
    [TestCase("Uganda", "img/flags/uganda.png")]
    [TestCase("Ukraine", "img/flags/ukraine.png")]
    [TestCase("United Arab Emirates", "img/flags/united-arab-emirates.png")]
    [TestCase("United Kingdom", "img/flags/united-kingdom.png")]
    [TestCase("United States", "img/flags/united-states.png")]
    [TestCase("Uruguay", "img/flags/uruguay.png")]
    [TestCase("Uzbekistan", "img/flags/uzbekistan.png")]
    [TestCase("Vanuatu", "img/flags/vanuatu.png")]
    [TestCase("Venezuela", "img/flags/venezuela.png")]
    [TestCase("Vietnam", "img/flags/vietnam.png")]
    [TestCase("Western Sahara", "img/flags/western-sahara.png")]
    [TestCase("Yemen", "img/flags/yemen.png")]
    [TestCase("Zambia", "img/flags/zambia.png")]
    [TestCase("Zimbabwe", "img/flags/zimbabwe.png")]
    public void GetFlag_ShouldReturnCorrectFlagImage_WhenCountryExists(string country, string expected)
    {
        // Act
        var result = FlagHelper.GetFlag(country);

        // Assert
        Assert.That(result, Is.EqualTo(expected));
    }

}
